apiVersion: v1
kind: Pod
metadata:
  name: gpu-interactive
  namespace: dgx-s-bmu-soet-230512-restricted
  labels:
    app.kubernetes.io/name: local-storage
spec:
  containers:
  - name: gpu-container
    image: bmu-headnode:9443/nvcr.io/nvidia/pytorch:24.10-py3
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        cpu: "8"
        memory: "16Gi"
        nvidia.com/mig-1g.18gb: 1
      limits:
        cpu: "8"
        memory: "16Gi"
        nvidia.com/mig-1g.18gb: 1
    volumeMounts:
    - name: home-dir
      mountPath: /user-home
    - name: private-storage
      mountPath: /workspace
  volumes:
  - name: home-dir
    hostPath:
      path: /home/dgx-s-bmu-soet-230512
      type: Directory
  - name: private-storage
    hostPath:
      path: /workspace/private-storage/dgx-s-bmu-soet-230512
      type: DirectoryOrCreate
